### PR TITLE
Improve Views checkbox value handling

### PR DESCRIPTION
**Pull request by totten**
Port of https://github.com/civicrm/civicrm-drupal/pull/448

### CODE REVIEW

**Comment by totten** [comment]
@herbdool @seamuslee001 @davejenx I've done a rote/untested port of the fix from D7 -- but not sure the best way to to test. Does this look right / work?

**Comment by seamuslee001** [comment]
Looking over this I think it makes sense to be.  @totten @herbdool @davejenx

**Comment by herbdool** [comment]
@totten After seeing the fix I had made one directly to the repo a couple days ago: https://github.com/civicrm/civicrm-backdrop/commit/b44d21cf529d516cf558f45d083487015cf50e3e -- I would normally do a PR but figured it was a simple, urgent fix. I haven't tested either.

I'm curious why this PR doesn't see conflicts with master.

**Comment by totten** [comment]
@herbdool ah, good to know it's already in `master`. I hadn't noticed.

There are probably a couple considerations in why you don't see a conflict with `master`:

 1. At the time that you put it in `1.x-master`, that was probably the right thing to do.
 2. But we had a few criticals `4.7.21` and decided to do an emergency `4.7.22` release. Too much has gone into `master` to use that for an emergency, so we had to improvise and make `4.7.22` from `4.7.21`.
 3. If you run `git branch --contains b44d21c` or `git tag --contains b44d21c`, it should show that `1.x-master` has b44d21c while `1.x-4.7.22-rc` doesn't have it.
 4. IIRC... if you apply the exact same patch in separate branches (e.g. `1.x-4.7.22-rc` and `1.x-master`) and then merge the branches, there won't be a conflict.

**Pull request merged**
