### PR TITLE
Issue 110: bring up to date with 7.x-5.22.1

### PR DESCRIPTION
**Pull request by herbdool**
https://github.com/civicrm/civicrm-backdrop/issues/110

### CODE REVIEW

**Comment by herbdool** [comment]
@seamuslee001 I'm assuming the build bot doesn't work yet for Backdrop. I can't recall if it was fixed. thx

**Comment by herbdool** [comment]
@laryn interested in testing this? Or anyone else?

**Comment by seamuslee001** [comment]
@herbdool the buildbot works for backdrop the issue is that it thinks there is conflicts, can you try and rebase against current master?

**Comment by herbdool** [comment]
@seamuslee001 gotcha. Just rebased but now it looks like I lost a bunch of changes. So gotta try again.

**Pull request closed without merging**
