### PR TITLE
1.x 5.11

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@herbdool the next release drops tomorrow - I think it needs to include this but I'd be happier if you gave it a quick test before we merge it

**Comment by herbdool** [comment]
@eileenmcnaughton @seamuslee001  I did a quick test of the PR. I added a custom file field to contacts and uploaded a file. Then I created a view of contacts and added the custom file field. I get an error: the field is broken/missing. 

I do *not* get the same error *without* the patch.

The PR seems to be same as for D7 so I'm not sure what's going wrong here. Does it work in D7?

**Comment by seamuslee001** [comment]
@herbdool can you just try clearing cache locally just in case? note that this code was released in the 5.10.3 sec release AFAIK

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
I get the same problem @herbdool reports. The following error appears with the patch -- but seems OK without the patch.

screen shot 2019-03-06 at 2 46 02 pm

There's a class renamed in the patch. If I flip that back to the original class name, it seems better. It'll take a few minutes to properly vet it, though.

**Comment by totten** [comment]
The autoloader was misconfigured (incorrect class=>file mapping). Autoloading on D7 works differently, which is why it wasn't an issue there. It's kind of a crazy happenstance that it worked before. Fixed for me by 5128c6c .

**Comment by herbdool** [comment]
@totten thanks, I had looked at autoload hook too but couldn't tell the issue before I had to break to make dinner

**Comment by totten** [comment]
Reported test failures appear to be unrelated. (`E2E_Extern_RestTest` fails with or without the patch -- on 5.11, 5.10, 5.7.)

**Comment by totten** [comment]
@herbdool yeah, that autoload typo is a subtle one! No way I would'a seen that without this error and some symbols to grep on.

Thanks for testing and pushing us toward the fix. 👍

**Pull request merged**
