### PR TITLE
Issue 135: add layout access visibility condition for CiviCRM URLs.

### LINKED ISSUE #135: Feature request: Layout access conditions that consider query parameters
[A recent forum post](https://forum.backdropcms.org/forum/how-configure-layout-civicrm-pages) asked for a way to put a donation block on a single CiviCRM event page. This is an example of a broader need, of being able to customize specific CiviCRM pages with layouts and blocks. Elsewhere in Backdrop, we could use a _URL path_ visibility condition for that, but since CiviCRM uses query parameters to distinguish pages and the URL path visibility condition doesn't consider query parameters part of the URL path, the URL path visibility condition won't work for that. So there is a need for a visibility condition that considers query parameters.

PR to follow.

### PR DESCRIPTION
**Pull request by bugfolder**
Fixes https://github.com/civicrm/civicrm-backdrop/issues/135.

This is a rebase of https://github.com/civicrm/civicrm-backdrop/pull/136 with some additions from the discussion of that PR.

### CODE REVIEW

**Comment by herbdool** [comment]
Thanks @bugfolder. I took a look. Maybe you had a good reason to create a new PR, though in general I think it's better to just update your existing PR so we keep the comment history.

The PR seems to work mostly as advertised. I tested it with both as a visibility condition on an entire layout and per individual block. I also tested the "allow access on the following pages" and the reverse.

I think we'll need to set a default for the two options (allow on following...). If it's not set it seems to always pass as TRUE regardless of the URL.

I got one idea while testing and wondering how hard it would be to implement: a wildcard. People might want to have a layout for all events. In which case they might want `civicrm/event/*` or `civicrm/event/info?id=*`. In Backdrop core this is done with `backdrop_match_path`.

**Comment by bugfolder** [comment]
> Maybe you had a good reason to create a new PR

I did. It needed rebasing, owing to the long time elapsed since first submission.

**Comment by herbdool** [comment]
You can rebase existing PRs too.

**Comment by bugfolder** [comment]
> I think we'll need to set a default for the two options (allow on following...). If it's not set it seems to always pass as TRUE regardless of the URL.

It has a default, but it wasn't showing due to a typo in the setting. Now fixed.

> I got one idea while testing and wondering how hard it would be to implement: a wildcard. People might want to have a layout for all events. In which case they might want civicrm/event/* or civicrm/event/info?id=*. In Backdrop core this is done with backdrop_match_path.

Let me ponder this a bit.

> You can rebase existing PRs too.

In theory, but every time I've tried that things end up garbled, so it's easier to start from a clean branch. (I'm obviously doing things rong when I try that.)

**Comment by bugfolder** [comment]
> People might want to have a layout for all events. In which case they might want civicrm/event/* or civicrm/event/info?id=*. 

They can do that without a wildcard, by just not including the "id=..." query parameters. Any query parameter that's not present matches on all possible values of that query parameter.

**Comment by herbdool** [comment]
I see. Can you provide a full example so I understand correctly? Are you saying enter: `civicrm/event/info?id=`

Whatever it is we should add that to the help text.

**Comment by herbdool** [comment]
I think I can answer my own question after testing. To match for all URLs like `civicrm/event/info?id=1`, `civicrm/event/info?id=2` and so on, this works: `civicrm/event/info` but not `civicrm/event/info?id=`.

I think I'll update the help text. Then I think this is okay to merge.

**Comment by bugfolder** [comment]
Sorry, I missed your follow-up question, but you've got the answer. Glad to see this moving.

**Pull request merged**
