### PR TITLE
Issue #11: Add Views Plugin for Civi ID from logged in person.

### PR DESCRIPTION
**Pull request by laryn**
Fixes https://lab.civicrm.org/dev/backdrop/-/issues/11

### CODE REVIEW

**Comment by laryn** [comment]
My attempt to simplify this down to `return CRM_Core_Session::getLoggedInContactID();` doesn't seem to actually work, likely due to permissions I'm guessing. I'll revert to the earlier version.

**Comment by eileenmcnaughton** [comment]
@herbdool is this on your radar?

**Comment by herbdool** [comment]
@laryn I merged the bug so you can remove it from this PR

**Comment by laryn** [comment]
@herbdool I rebased the PR.

**Comment by herbdool** [comment]
@laryn thanks!

**Pull request merged**
