### PR TITLE
Issue #8 CiviCRM link in admin bar

### PR DESCRIPTION
**Pull request by herbdool**
Short n sweet

### CODE REVIEW

**Comment by herbdool** [comment]
@quicksketch this was a quick fix

**Comment by colemanw** [comment]
Thanks. Can you also update the fn docblock with the correct hook name?

**Comment by herbdool** [comment]
Thanks for catching that @colemanw -- not sure if you prefer this to be rebased or not.

**Comment by colemanw** [comment]
With something small like this I usually do

```
git commit -a --amend
git push -f
```

**Comment by herbdool** [comment]
Right I forgot about _forcing_ the push of the amended commit. Last time I did the amend and pushed it compained and so I pulled and pushed, which just made a mess of things.

**Comment by colemanw** [comment]
No biggie. Next time.

**Pull request merged**
