### PR TITLE
#60: Allow webform images to use image styles

### PR DESCRIPTION
**Pull request by laryn**
https://github.com/civicrm/civicrm-backdrop/issues/60

### CODE REVIEW

**Comment by herbdool** [comment]
Hopefully I'll get a chance in a week or so to test this. But looks good.

You'll have to fix the syntax to match CiviCRM's guidelines.

**Comment by laryn** [comment]
Not able to load the details of the failures right now for some reason. 
> screen shot 2019-02-25 at 4 07 16 pm

**Comment by laryn** [comment]
Jenkins re test this please

**Comment by herbdool** [comment]
Jenkins retest this please

**Comment by herbdool** [comment]
@laryn I think there's a problem with Jenkins on this repo.

cc @eileenmcnaughton

**Comment by herbdool** [comment]
I tried testing first the patch with just the core contact image. It doesn't seem to work for me, but could be a problem with my local Civi install (doesn't work well in Lando). I don't quite understand how it works, neither the original nor the patch. I might have take a look later.

**Comment by laryn** [comment]
No problem. Does it work without the patch on a core image? If memory serves the core image functionality wasn't even working for me before this patch (but I could be wrong about that).

The original basically gets the CiviCRM upload path and uses that to try to peel off the image name from the URL (whatever comes after `photo=` in the URL) and then tries to style that. The patch extends that to look in the private or public upload directories (which webform uploads to) and use the same technique to pull off the filenames from those.

**Comment by eileenmcnaughton** [comment]
@totten ^^ jenkins q

**Comment by herbdool** [comment]
@laryn it didn't work for me without the patch either.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by laryn** [comment]
@herbdool It looks like I forgot to tag you after I updated the PR. If you get a chance to test again I'd be interested to know if it's working for you now.

**Comment by laryn** [comment]
I just tested this again on one of my sites after updating CiviCRM. All my images in a CiviCRM View disappeared -- copying the changes and patching brought them all back right away.

**Pull request merged**
