### PR TITLE
Convert member and group association rules to config, drop tables, and clean up docblocks

### PR DESCRIPTION
**Pull request by herbdool**
Fixes https://lab.civicrm.org/dev/backdrop/-/issues/1

### CODE REVIEW

**Comment by herbdool** [comment]
@laryn would you be willing to look this PR over? I've tested and it's working well for me.

**Comment by laryn** [comment]
@herbdool I'll try to test next week.

**Comment by laryn** [comment]
This looks great. I haven't tested on live data yet, I'm sorry to say.

**Comment by eileenmcnaughton** [comment]
@herbdool I just looked at the backdrop PRs (which I don't often do) & saw this is sitting around & looks mergeable - but is fairly old. Is this still OK to merge as is

**Comment by herbdool** [comment]
I think it is good to merge, just fell off my radar. I have permission to merge so I'll do so.

**Pull request merged**
