### PR TITLE
Prepare info files of CiviCRM Contact Reference Field and CiviCRM The…

### PR DESCRIPTION
**Pull request by serundeputy**
…me for Backdrop CMS 1.x compatibility.

### CODE REVIEW

**Comment by serundeputy** [comment]
This duplicates @herbdool 's work closing.

**Comment by herbdool** [comment]
@serundeputy Do you know who has write access to this repo?

**Comment by serundeputy** [comment]
@herbdool I do not know; @jenlampton do you know?

**Comment by herbdool** [comment]
@totten @quicksketch do either of you have write access to civicrm-backdrop?

**Comment by quicksketch** [comment]
@jenlampton and I have commit access (but not owner access apparently), so I can merge PRs but I can't add new maintainers.

**Pull request closed without merging**
