### PR TITLE
CRM-21095: Make status messages work with Backdrop core CSS

### PR DESCRIPTION
**Pull request by laryn**
https://issues.civicrm.org/jira/browse/CRM-21095

### CODE REVIEW

**Comment by laryn** [comment]
It was also affecting the System Status notification in the footer on CiviCRM backend pages, so I've added another selector to better pinpoint the ones that need adjustment.

screen shot 2017-08-22 at 5 38 06 pm

**Comment by colemanw** [comment]
Looks good to me.

**Comment by colemanw** [comment]
Actually @laryn a more "civi-ish" way to add the css would be to add this function to the `CRM_Utils_System_Backdrop` class: https://github.com/civicrm/civicrm-core/blob/4.7.23/CRM/Utils/System/DrupalBase.php#L303-L310

Note that you'd be overriding the existing implementation so you'd need to decide whether that drupal.js file is still needed in backdrop or not and call the parent function if so.

**Comment by laryn** [comment]
@colemanw 
You mean something like this?

```
  public function appendCoreResources(&$list) {
    $list[] = 'js/crm.drupal.js';
    $list[] = 'css/civicrm-backdrop.css';
  }
```

**Comment by colemanw** [comment]
Yes. Although the drupal.js might not be relevant to Backdrop - it only contains a D7-specific hack and a D8 hack.

**Comment by laryn** [comment]
@colemanw I will make an alternative PR over at civicrm-core and post back here.

**Comment by herbdool** [comment]
Yeah, seems like we can drop crm.drupal.js. Those selectors don't exist in Backdrop.

Though we might want a separate PR to make the Backdrop admin bar play nice with the CiviCRM admin bar. Prevent the dropdown menus from opening behind the CiviCRM menu.

**Comment by laryn** [comment]
@colemanw If the one linked below looks good, this one can be unmerged.

https://github.com/civicrm/civicrm-core/pull/10891

@herbdool Thanks! I've left out the .js file. And yes, we may want to add something to this CSS file (once finalized) to fix that menu issue.

**Pull request merged**
